--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SrClau/LobbyCore
build-by-default: true
branches:
- main
projects:
  LobbyCore:
    path: ""
    icon: "resources/images/icon.png"
...
