contact_links:
  - name: Help & support on Discord
    url: https://discord.gg/Js63vy7
    about: kskdkd.
  - name: Help & support on forums
    url: https://discord.gg/Js63vy7
    about:  ndndksk
  - name: Documentation
    url: https://discord.gg/Js63vy7
    about: hsjjsj
