contact_links:
  - name: Support on Discord
    url: https://discord.gg/Js63vy7
    about: Receive support in our discord
  - name: Support on Wikis
    url: https://discord.gg/Js63vy7
    about: We do not have for now to send you our discord
  - name: Documentation
    url: https://github.com/SrClau/LobbyCore/README.md
    about: Our documentation :D
